pool:
  name: 'default'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'meritodgnew'
    repository: 'SalesBookWeb'
    command: 'buildAndPush'
    Dockerfile: '**/SalesBookWeb/Dockerfile'